/* Fruits — climat tempéré Centre / Ouest de la France
   Petits fruits, fruitiers et fruits d'été du potager.

   Les arbres et arbustes portent en plus un bloc "arbre" :
     pollinisation · taille · forme · premiere (années avant la 1re récolte)

   Note : la rhubarbe est botaniquement un légume (on mange le pétiole de la
   feuille), mais elle se cuisine en dessert — elle est donc rangée ici. */

const FRUITS = [

/* ================= FRUITS DU POTAGER ================= */

{ id:"fraisier", nom:"Fraisier", latin:"Fragaria x ananassa", cat:"fruit", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[3,4,8,9,10], re:[5,6,7,8,9],
  expo:"Soleil, mi-ombre en climat chaud", sol:"Riche en humus, acide, drainé", eau:"Régulier au pied",
  esp:"30 cm sur le rang, 50 cm entre rangs", prof:"Collet au ras du sol", lev:"—", cyc:"1 an",
  amis:["Ail","Oignon","Poireau","Épinard","Bourrache officinale","Thym"],
  ennemis:["Chou pommé","Pomme de terre","Tomate"],
  perma:"Paille sous les fruits (d'où le nom !) pour éviter la pourriture. Les stolons donnent des plants gratuits à repiquer en août. Renouvelle la plantation tous les 3 ans.",
  conseils:"La bourrache plantée à côté attire les pollinisateurs et augmente nettement la récolte." },

{ id:"melon", nom:"Melon", latin:"Cucumis melo", cat:"fruit", fam:"Cucurbitacées", viv:false,
  sa:[3,4], sp:[5], pl:[5,6], re:[7,8,9],
  expo:"Plein soleil, très chaud", sol:"Riche, drainé, réchauffé", eau:"Régulier puis stop 15 jours avant récolte",
  esp:"1 m en tous sens", prof:"2 cm", lev:"5 à 8 jours", cyc:"4 mois",
  amis:["Maïs doux","Capucine","Bourrache officinale","Basilic"],
  ennemis:["Concombre","Pomme de terre"],
  perma:"Sous bâche ou paillage sombre pour réchauffer le sol. Une seule tige avec 4-5 fruits maximum.",
  conseils:"Mûr quand le pédoncule se craquelle et que l'odeur devient forte." },

{ id:"pasteque", nom:"Pastèque", latin:"Citrullus lanatus", cat:"fruit", fam:"Cucurbitacées", viv:false,
  sa:[3,4], sp:[5], pl:[5,6], re:[8,9],
  expo:"Plein soleil, le coin le plus chaud", sol:"Riche, sableux, très réchauffé", eau:"Abondant jusqu'à la grosseur, puis stop",
  esp:"1,5 m en tous sens", prof:"3 cm", lev:"6 à 10 jours", cyc:"4 à 5 mois",
  amis:["Maïs doux","Capucine","Bourrache officinale"],
  ennemis:["Concombre","Pomme de terre"],
  perma:"Encore plus exigeante en chaleur que le melon : réserve-lui la meilleure exposition, avec un paillage noir. Sous climat frais, une serre s'impose.",
  conseils:"Mûre quand la vrille la plus proche du fruit est sèche et que le dessous vire au jaune crème. Le son doit être creux." },

{ id:"physalis", nom:"Physalis (coqueret du Pérou)", latin:"Physalis peruviana", cat:"fruit", fam:"Solanacées", viv:false,
  sa:[2,3], sp:[], pl:[5], re:[8,9,10],
  expo:"Plein soleil, abrité", sol:"Ordinaire, drainé, pas trop riche", eau:"Modéré",
  esp:"80 cm en tous sens", prof:"0,5 cm", lev:"15 à 20 jours", cyc:"5 mois",
  amis:["Œillet d'Inde","Basilic"],
  ennemis:["Pomme de terre","Tomate"],
  perma:"Solanacée comme la tomate : à faire entrer dans la même rotation, jamais deux ans au même endroit. Un seul pied donne des centaines de fruits.",
  conseils:"Ne récolte que les fruits tombés au sol, dans leur lampion sec : c'est le seul signe fiable de maturité. Se conserve des semaines dans son enveloppe." },

{ id:"rhubarbe", nom:"Rhubarbe", latin:"Rheum rhabarbarum", cat:"fruit", fam:"Polygonacées", viv:true,
  sa:[], sp:[], pl:[3,4,10,11], re:[4,5,6,7],
  expo:"Mi-ombre", sol:"Très riche, frais, profond", eau:"Généreux",
  esp:"1,2 m en tous sens", prof:"Bourgeon affleurant", lev:"—", cyc:"1re récolte la 2e année",
  amis:["Chou pommé","Haricot nain","Ail"],
  ennemis:[],
  perma:"Vivace de 10 ans et plus. Un seau de compost chaque automne au pied et elle produit sans rien demander. Les feuilles (toxiques à manger) font un excellent paillage ou purin anti-pucerons.",
  conseils:"Ne jamais couper : tire sur le pétiole en le tournant. Ne récolte pas la 1re année. Coupe les fleurs dès leur apparition." },

/* ================= PETITS FRUITS ================= */

{ id:"framboisier", nom:"Framboisier", latin:"Rubus idaeus", cat:"fruit", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[10,11,12,2,3], re:[6,7,8,9],
  expo:"Mi-ombre", sol:"Frais, humifère, acide, drainé", eau:"Régulier",
  esp:"50 cm sur le rang, 1,5 m entre rangs", prof:"Collet au ras du sol", lev:"—", cyc:"1 an",
  amis:["Ail","Œillet d'Inde","Ciboulette"],
  ennemis:["Pomme de terre","Tomate"],
  perma:"Drageonne beaucoup : délimite le rang et donne les drageons en trop. Paillage permanent de compost et de feuilles mortes, il déteste le sol nu et travaillé (racines superficielles).",
  conseils:"Remontant : coupe les tiges ayant fructifié après la 2e récolte. Non remontant : coupe à ras les tiges qui ont produit, garde les jeunes.",
  arbre:{ pollinisation:"Autofertile, un seul pied suffit", taille:"Chaque hiver : supprimer les tiges qui ont fructifié", forme:"Rang palissé sur deux fils", premiere:"Dès la 1re année pour les remontants" },
  med:{ partie:"Feuilles", bienfaits:["Prépare l'accouchement (tonique de l'utérus, dernier trimestre)","Règles douloureuses","Diarrhée légère (astringent)","Maux de gorge en gargarisme"],
        usage:"Infusion de feuilles séchées : 1 cuillère à soupe par tasse, 10 min.",
        precautions:"À ne PAS utiliser en début de grossesse — uniquement sur les dernières semaines, et avec l'accord d'une sage-femme." } },

{ id:"groseillier", nom:"Groseillier à grappes", latin:"Ribes rubrum", cat:"fruit", fam:"Grossulariacées", viv:true,
  sa:[], sp:[], pl:[10,11,12,2,3], re:[6,7],
  expo:"Mi-ombre, il craint le soleil brûlant", sol:"Frais, humifère, plutôt lourd", eau:"Régulier en été",
  esp:"1,2 m entre pieds", prof:"Collet à 5 cm sous le sol", lev:"—", cyc:"2 ans",
  amis:["Ciboulette","Ail","Capucine"],
  ennemis:[],
  perma:"L'arbuste idéal des coins mi-ombragés où rien d'autre ne fructifie. Se bouture en novembre les doigts dans le nez : une tige de 20 cm plantée en terre, et c'est un nouveau pied.",
  conseils:"Récolte la grappe entière en la pinçant à la base, jamais grain par grain.",
  arbre:{ pollinisation:"Autofertile", taille:"En hiver : supprimer le bois de plus de 4 ans et aérer le centre", forme:"Buisson ou cordon le long d'un mur", premiere:"2 ans" } },

{ id:"cassissier", nom:"Cassissier", latin:"Ribes nigrum", cat:"fruit", fam:"Grossulariacées", viv:true,
  sa:[], sp:[], pl:[10,11,12,2,3], re:[6,7],
  expo:"Mi-ombre", sol:"Frais, riche, profond", eau:"Régulier, il souffre vite de la sécheresse",
  esp:"1,5 m entre pieds", prof:"Collet à 5 cm sous le sol", lev:"—", cyc:"2 ans",
  amis:["Ciboulette","Ail"],
  ennemis:["Pin (hôte de la rouille)"],
  perma:"Le plus gourmand des petits fruits : compost généreux chaque automne. Ses fleurs très précoces nourrissent les bourdons quand presque rien n'est ouvert.",
  conseils:"Fructifie surtout sur le bois de l'année précédente : taille sévèrement le vieux bois pour forcer les jeunes pousses.",
  arbre:{ pollinisation:"Autofertile, mais deux variétés donnent de plus grosses grappes", taille:"Chaque hiver : retirer un tiers des plus vieilles branches à la base", forme:"Buisson", premiere:"2 ans" },
  med:{ partie:"Feuilles, fruits", bienfaits:["Douleurs articulaires, rhumatismes (feuilles)","Très riche en vitamine C (fruits)","Fatigue, circulation","Diurétique doux"],
        usage:"Infusion de feuilles séchées : 1 cuillère à soupe par tasse, 10 min, en cure de 3 semaines. Les fruits frais ou en sirop pour la vitamine C.",
        precautions:"Effet diurétique : prudence en cas de traitement pour la tension ou le cœur." } },

{ id:"groseillier-maquereau", nom:"Groseillier à maquereau", latin:"Ribes uva-crispa", cat:"fruit", fam:"Grossulariacées", viv:true,
  sa:[], sp:[], pl:[10,11,12,2,3], re:[6,7],
  expo:"Mi-ombre", sol:"Frais, humifère", eau:"Régulier",
  esp:"1,2 m entre pieds", prof:"Collet à 5 cm sous le sol", lev:"—", cyc:"2 ans",
  amis:["Ciboulette","Ail"],
  ennemis:[],
  perma:"Épineux : à placer en bordure, il fait une haie défensive comestible et abrite les oiseaux. Très rustique, il tient jusqu'à -25°C.",
  conseils:"Cueille avec des gants. Récolté vert il fait d'excellentes tartes, laissé mûrir il devient sucré et se mange cru.",
  arbre:{ pollinisation:"Autofertile", taille:"Aérer le centre en hiver pour limiter l'oïdium, qui est son seul vrai ennemi", forme:"Buisson sur tige courte", premiere:"2 ans" } },

{ id:"murier", nom:"Mûrier sans épines", latin:"Rubus fruticosus", cat:"fruit", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[10,11,2,3], re:[8,9,10],
  expo:"Soleil ou mi-ombre", sol:"Tous types, même pauvre", eau:"Faible une fois installé",
  esp:"2 m entre pieds, palissé", prof:"Collet au ras du sol", lev:"—", cyc:"2 ans",
  amis:[],
  ennemis:[],
  perma:"Increvable et très productif : un seul pied nourrit une famille en confitures. Palissé sur un grillage, il fait une clôture infranchissable et un garde-manger pour les oiseaux. Choisis une variété sans épines, tu t'en féliciteras à chaque cueillette.",
  conseils:"Comme le framboisier : les tiges qui ont fructifié meurent, on les coupe à ras après la récolte.",
  arbre:{ pollinisation:"Autofertile", taille:"Après récolte : couper à ras les tiges qui ont produit, palisser les jeunes", forme:"Palissé sur fils ou grillage", premiere:"2 ans" } },

{ id:"myrtillier", nom:"Myrtillier", latin:"Vaccinium corymbosum", cat:"fruit", fam:"Éricacées", viv:true,
  sa:[], sp:[], pl:[10,11,2,3], re:[7,8,9],
  expo:"Soleil doux, mi-ombre", sol:"IMPÉRATIVEMENT acide (pH 4 à 5), terre de bruyère", eau:"Régulier, à l'eau de pluie",
  esp:"1,5 m entre pieds", prof:"Collet au ras du sol", lev:"—", cyc:"3 ans",
  amis:[],
  ennemis:[],
  perma:"Le seul de la liste qui ne s'adapte pas : en sol calcaire il jaunit et meurt, sans discussion. Réserve-lui un grand bac de terre de bruyère, ou renonce. Arrose à l'eau de pluie, celle du robinet est souvent calcaire.",
  conseils:"Paillage permanent d'aiguilles de pin ou d'écorces, qui maintient l'acidité. Les fruits mûrissent progressivement : plusieurs passages.",
  arbre:{ pollinisation:"Deux variétés différentes doublent la récolte", taille:"Légère, après 4 ans : retirer les plus vieilles branches", forme:"Buisson", premiere:"3 ans" } },

{ id:"vigne", nom:"Vigne (raisin de table)", latin:"Vitis vinifera", cat:"fruit", fam:"Vitacées", viv:true,
  sa:[], sp:[], pl:[11,12,2,3], re:[9,10],
  expo:"Plein soleil, contre un mur au sud", sol:"Drainé, caillouteux, même pauvre", eau:"Aucun une fois installée",
  esp:"1,5 m entre pieds", prof:"Point de greffe au-dessus du sol", lev:"—", cyc:"3 ans",
  amis:["Hysope","Ciboulette"],
  ennemis:["Chou pommé"],
  perma:"Parfaite sur une pergola ou une tonnelle : elle donne de l'ombre en été, laisse passer le soleil en hiver, et produit. Ses racines descendent très profond, elle ne concurrence pas les cultures voisines.",
  conseils:"Taille en hiver, hors gel, sinon elle « pleure ». Effeuille légèrement autour des grappes en août pour les faire mûrir.",
  arbre:{ pollinisation:"Autofertile", taille:"Indispensable, chaque hiver : garder 2 yeux par courson, sinon elle part partout et ne produit plus", forme:"Palissée, cordon ou tonnelle", premiere:"3 ans" } },

{ id:"kiwai", nom:"Kiwaï (kiwi de Sibérie)", latin:"Actinidia arguta", cat:"fruit", fam:"Actinidiacées", viv:true,
  sa:[], sp:[], pl:[10,11,3,4], re:[9,10],
  expo:"Soleil, abrité des vents froids", sol:"Riche, frais, drainé, plutôt acide", eau:"Régulier en été",
  esp:"3 m entre pieds", prof:"Collet au ras du sol", lev:"—", cyc:"3 à 4 ans",
  amis:[],
  ennemis:[],
  perma:"Liane vigoureuse qui couvre une pergola en deux saisons et résiste à -25°C. Les fruits, petits et à peau lisse, se mangent sans éplucher.",
  conseils:"ATTENTION : il faut un pied mâle pour trois à six pieds femelles, sauf variété autofertile (Issaï). C'est l'erreur classique qui fait attendre des fruits pendant des années.",
  arbre:{ pollinisation:"Pieds mâle ET femelle nécessaires (sauf variété Issaï, autofertile)", taille:"En hiver, sévère : c'est une liane qui fait 10 m si on la laisse", forme:"Sur pergola ou treille solide", premiere:"3 à 4 ans" } },

{ id:"noisetier", nom:"Noisetier", latin:"Corylus avellana", cat:"fruit", fam:"Bétulacées", viv:true,
  sa:[], sp:[], pl:[10,11,12,2,3], re:[9,10],
  expo:"Soleil ou mi-ombre", sol:"Tous types, drainé", eau:"Aucun une fois installé",
  esp:"4 m entre pieds", prof:"Collet au ras du sol", lev:"—", cyc:"3 à 4 ans",
  amis:[],
  ennemis:[],
  perma:"Pilier de la haie champêtre : brise-vent, refuge des auxiliaires, et ses tailles fournissent tuteurs et bois raméal fragmenté (BRF) pour le potager. Ses chatons donnent le premier pollen de l'année aux abeilles, dès février.",
  conseils:"Plante au moins deux variétés différentes : seul, il produit très peu. Le principal concurrent, c'est l'écureuil — récolte dès que les noisettes se détachent facilement.",
  arbre:{ pollinisation:"Deux variétés différentes indispensables", taille:"Supprimer les rejets du pied chaque hiver, aérer le centre", forme:"Cépée ou arbuste", premiere:"3 à 4 ans" } },

/* ================= FRUITIERS ================= */

{ id:"pommier", nom:"Pommier", latin:"Malus domestica", cat:"fruit", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[11,12,1,2,3], re:[8,9,10,11],
  expo:"Soleil", sol:"Profond, frais, drainé", eau:"Les 2 premières années, puis aucun",
  esp:"3 m en basse tige, 8 m en haute tige", prof:"Point de greffe 10 cm au-dessus du sol", lev:"—", cyc:"3 à 5 ans",
  amis:["Ciboulette","Capucine","Consoude officinale","Achillée millefeuille"],
  ennemis:[],
  perma:"Autour du pied, un cercle de consoude, d'achillée et de ciboulette : elles nourrissent l'arbre, attirent les auxiliaires et limitent la tavelure. C'est la base du « guilde » en permaculture. Ne jamais laisser l'herbe pousser contre le tronc les premières années.",
  conseils:"Le point de greffe doit rester au-dessus du sol, sinon l'arbre s'affranchit et devient énorme. Contre le carpocapse (le ver de la pomme), pièges à phéromones en mai et juillet.",
  arbre:{ pollinisation:"Deux variétés qui fleurissent en même temps sont nécessaires", taille:"En hiver : aérer, supprimer le bois mort et les branches qui se croisent", forme:"Basse tige pour cueillir sans échelle, haute tige pour du long terme", premiere:"3 à 5 ans" } },

{ id:"poirier", nom:"Poirier", latin:"Pyrus communis", cat:"fruit", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[11,12,1,2,3], re:[8,9,10],
  expo:"Soleil, abrité — il fleurit tôt", sol:"Profond, frais, un peu plus lourd que pour le pommier", eau:"Les 2 premières années",
  esp:"3 m en basse tige, 6 m en haute tige", prof:"Point de greffe au-dessus du sol", lev:"—", cyc:"4 à 6 ans",
  amis:["Ciboulette","Consoude officinale","Capucine"],
  ennemis:[],
  perma:"Fleurit avant le pommier : plus exposé aux gelées tardives, il mérite le coin le plus abrité du jardin. Excellent palissé contre un mur au sud, où il gagne en précocité.",
  conseils:"Les poires ne mûrissent pas sur l'arbre : cueille-les fermes quand le pédoncule se détache d'un geste, et laisse-les finir à la cave.",
  arbre:{ pollinisation:"Deux variétés compatibles nécessaires", taille:"En hiver, plus légère que le pommier", forme:"Basse tige, ou palissé en espalier", premiere:"4 à 6 ans" } },

{ id:"prunier", nom:"Prunier", latin:"Prunus domestica", cat:"fruit", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[11,12,2,3], re:[7,8,9],
  expo:"Soleil", sol:"Tous types, même argileux", eau:"Les 2 premières années",
  esp:"4 m entre arbres", prof:"Point de greffe au-dessus du sol", lev:"—", cyc:"3 à 4 ans",
  amis:["Ciboulette","Consoude officinale"],
  ennemis:[],
  perma:"Le plus facile des fruitiers de nos régions : il pousse presque partout et produit énormément. Drageonne parfois : les rejets se replantent ailleurs.",
  conseils:"Taille le moins possible, et JAMAIS en hiver : les Prunus se taillent en été, après récolte, sinon les plaies attirent la gommose. Éclaircis les fruits en juin si les branches ploient.",
  arbre:{ pollinisation:"Souvent autofertile (Reine-Claude, Mirabelle), mais un second arbre améliore", taille:"En été après récolte, jamais en hiver", forme:"Demi-tige", premiere:"3 à 4 ans" } },

{ id:"cerisier", nom:"Cerisier", latin:"Prunus avium", cat:"fruit", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[11,12,2,3], re:[6,7],
  expo:"Soleil", sol:"Profond, drainé, il déteste l'eau stagnante", eau:"Les 2 premières années",
  esp:"5 m entre arbres", prof:"Point de greffe au-dessus du sol", lev:"—", cyc:"4 à 5 ans",
  amis:["Ciboulette","Consoude officinale"],
  ennemis:[],
  perma:"Magnifique en fleurs et très mellifère, mais il devient grand : prévois la place, ou choisis un porte-greffe nanifiant. Les oiseaux prendront leur part — plante-le en pensant à la partager.",
  conseils:"Comme le prunier : taille en été après récolte, jamais en hiver. Contre la mouche de la cerise, privilégie les variétés précoces, récoltées avant qu'elle ne sévisse.",
  arbre:{ pollinisation:"La plupart demandent un second cerisier compatible ; quelques variétés sont autofertiles", taille:"En été après récolte, le moins possible", forme:"Demi-tige ou haute tige", premiere:"4 à 5 ans" } },

{ id:"pecher", nom:"Pêcher", latin:"Prunus persica", cat:"fruit", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[11,12,2,3], re:[7,8,9],
  expo:"Plein soleil, contre un mur au sud", sol:"Léger, drainé, plutôt sableux", eau:"Régulier en été",
  esp:"4 m entre arbres", prof:"Point de greffe au-dessus du sol", lev:"—", cyc:"2 à 3 ans",
  amis:["Ail","Ciboulette","Capucine"],
  ennemis:[],
  perma:"Ail et ciboulette plantés au pied limitent réellement la cloque, sa maladie chronique. Décoction de prêle dès le gonflement des bourgeons, en février, en préventif. Durée de vie courte : une quinzaine d'années.",
  conseils:"Produit sur le bois de l'année précédente : sans taille annuelle, la production se déplace vers l'extérieur et s'effondre. Éclaircis à une pêche tous les 15 cm.",
  arbre:{ pollinisation:"Autofertile", taille:"Chaque année, en fin d'hiver, avant floraison", forme:"Gobelet, ou palissé contre un mur", premiere:"2 à 3 ans" } },

{ id:"figuier", nom:"Figuier", latin:"Ficus carica", cat:"fruit", fam:"Moracées", viv:true,
  sa:[], sp:[], pl:[3,4,10,11], re:[7,8,9,10],
  expo:"Plein soleil, contre un mur au sud", sol:"Drainé, même pauvre et caillouteux", eau:"Aucun une fois installé",
  esp:"4 m, ou grand bac", prof:"Collet au ras du sol", lev:"—", cyc:"2 à 3 ans",
  amis:[],
  ennemis:[],
  perma:"Se bouture avec une facilité déconcertante : une branche de 30 cm plantée en terre à l'automne fait un arbre. Un sol pauvre et sec donne des figues plus sucrées qu'un sol riche — ne le nourris surtout pas.",
  conseils:"Sous climat frais, choisis une variété bifère (deux récoltes) et plante-le contre un mur qui restitue la chaleur la nuit. Paille le pied les premiers hivers.",
  arbre:{ pollinisation:"Autofertile sous nos climats", taille:"Très légère, en fin d'hiver : il déteste être taillé sévèrement", forme:"Buisson ou palissé contre un mur", premiere:"2 à 3 ans" } }

];
