/* Légumes du potager — climat tempéré Centre / Ouest de la France
   Mois : 1 = janvier ... 12 = décembre
   sa = semis sous abri | sp = semis en pleine terre | pl = plantation/repiquage | re = récolte */

const LEGUMES = [

{ id:"tomate", nom:"Tomate", latin:"Solanum lycopersicum", cat:"legume", fam:"Solanacées", viv:false,
  sa:[2,3,4], sp:[], pl:[5], re:[7,8,9,10],
  expo:"Plein soleil", sol:"Riche, profond, bien drainé", eau:"Régulier au pied, jamais sur le feuillage",
  esp:"50 cm entre pieds, 80 cm entre rangs", prof:"0,5 cm", lev:"6 à 10 jours", cyc:"4 à 5 mois",
  amis:["Basilic","Œillet d'Inde","Persil","Carotte","Capucine","Ail"],
  ennemis:["Pomme de terre","Chou pommé","Fenouil bulbeux","Maïs doux"],
  perma:"Paille épaisse au pied dès juin pour garder l'humidité. Purin d'ortie à la plantation, purin de consoude à la fructification. Ne jamais replanter au même endroit avant 4 ans (mildiou).",
  conseils:"Repiquer en godet dès 2 vraies feuilles. Sortir seulement après les Saints de Glace (mi-mai). Enterrer la tige jusqu'aux premières feuilles : elle fera des racines supplémentaires." },

{ id:"courgette", nom:"Courgette", latin:"Cucurbita pepo", cat:"legume", fam:"Cucurbitacées", viv:false,
  sa:[4], sp:[5,6], pl:[5,6], re:[7,8,9,10],
  expo:"Plein soleil", sol:"Très riche en compost, frais", eau:"Abondant, au pied",
  esp:"1 m en tous sens", prof:"2 cm", lev:"5 à 8 jours", cyc:"2 mois",
  amis:["Haricot nain","Maïs doux","Capucine","Bourrache officinale","Souci officinal (Calendula)"],
  ennemis:["Pomme de terre","Concombre"],
  perma:"Plante-la directement sur un tas de compost mûr. Trio permaculture classique : maïs + haricot grimpant + courge. Récolte tous les 2-3 jours, sinon la plante arrête de produire.",
  conseils:"2 ou 3 pieds suffisent pour une famille. Semer 3 graines par poquet et garder le plus beau plant." },

{ id:"concombre", nom:"Concombre", latin:"Cucumis sativus", cat:"legume", fam:"Cucurbitacées", viv:false,
  sa:[3,4], sp:[5], pl:[5,6], re:[7,8,9],
  expo:"Plein soleil, abrité du vent", sol:"Riche, frais, humifère", eau:"Très régulier (amertume si à-coups)",
  esp:"60 cm, palissé de préférence", prof:"2 cm", lev:"5 à 10 jours", cyc:"3 mois",
  amis:["Haricot nain","Petit pois","Aneth","Bourrache officinale","Basilic"],
  ennemis:["Pomme de terre","Courgette","Tomate"],
  perma:"Fais-le grimper sur un treillis : gain de place, fruits droits et propres, bien moins de maladies. Paillage indispensable.",
  conseils:"Craint le froid : rien dehors avant mi-mai. Pincer au-dessus de la 4e feuille pour le faire ramifier." },

{ id:"aubergine", nom:"Aubergine", latin:"Solanum melongena", cat:"legume", fam:"Solanacées", viv:false,
  sa:[2,3], sp:[], pl:[5], re:[7,8,9,10],
  expo:"Plein soleil, très chaud", sol:"Riche et profond", eau:"Régulier et généreux",
  esp:"60 cm", prof:"0,5 cm", lev:"10 à 15 jours", cyc:"5 mois",
  amis:["Haricot nain","Thym","Estragon","Œillet d'Inde"],
  ennemis:["Pomme de terre","Tomate"],
  perma:"Exigeante en chaleur : serre ou coin le plus chaud du jardin. Tuteure et limite à 4-5 fruits par pied sous climat frais.",
  conseils:"Semis très précoce indispensable (février) pour récolter avant l'automne." },

{ id:"poivron", nom:"Poivron / Piment", latin:"Capsicum annuum", cat:"legume", fam:"Solanacées", viv:false,
  sa:[2,3], sp:[], pl:[5], re:[7,8,9,10],
  expo:"Plein soleil", sol:"Riche, léger, drainé", eau:"Modéré mais régulier",
  esp:"50 cm", prof:"0,5 cm", lev:"12 à 20 jours", cyc:"4 à 5 mois",
  amis:["Basilic","Œillet d'Inde","Carotte","Oignon"],
  ennemis:["Fenouil bulbeux","Haricot nain"],
  perma:"Aime la compagnie du basilic qui éloigne les pucerons. Paillage obligatoire, il déteste les racines sèches.",
  conseils:"Germe lentement et seulement au chaud (20-25°C). Récolte verte, ou attends la couleur pour plus de sucre et de vitamines." },

{ id:"haricot-nain", nom:"Haricot nain", latin:"Phaseolus vulgaris", cat:"legume", fam:"Fabacées", viv:false,
  sa:[], sp:[5,6,7], pl:[], re:[7,8,9,10],
  expo:"Soleil", sol:"Léger, aucune fumure nécessaire", eau:"Régulier à la floraison",
  esp:"10 cm sur le rang, 40 cm entre rangs", prof:"3 cm", lev:"6 à 10 jours", cyc:"2 mois",
  amis:["Carotte","Courgette","Concombre","Fraisier","Sarriette vivace","Maïs doux"],
  ennemis:["Ail","Oignon","Échalote","Poireau","Fenouil bulbeux"],
  perma:"Fixe l'azote de l'air dans le sol : c'est un engrais vert comestible. Laisse les racines en terre après récolte. Sème tous les 15 jours de mai à juillet pour récolter en continu.",
  conseils:"Ne jamais semer en terre froide (attends 12°C). Buttage léger quand les plants font 15 cm." },

{ id:"haricot-rame", nom:"Haricot à rames", latin:"Phaseolus vulgaris", cat:"legume", fam:"Fabacées", viv:false,
  sa:[], sp:[5,6], pl:[], re:[7,8,9,10],
  expo:"Soleil, abrité du vent", sol:"Léger, frais", eau:"Régulier",
  esp:"Poquets de 5-6 graines tous les 40 cm", prof:"3 cm", lev:"6 à 10 jours", cyc:"2,5 mois",
  amis:["Maïs doux","Courge butternut","Capucine","Sarriette vivace"],
  ennemis:["Ail","Oignon","Poireau","Betterave rouge"],
  perma:"Base des Trois Sœurs : le maïs sert de tuteur, le haricot apporte l'azote, la courge couvre le sol.",
  conseils:"Rames de 2 m minimum. Production 3 fois supérieure au haricot nain pour la même surface." },

{ id:"pois", nom:"Petit pois", latin:"Pisum sativum", cat:"legume", fam:"Fabacées", viv:false,
  sa:[], sp:[2,3,4,10,11], pl:[], re:[5,6,7],
  expo:"Soleil doux, mi-ombre l'été", sol:"Frais, jamais de fumier frais", eau:"Régulier à la floraison",
  esp:"5 cm sur le rang", prof:"3 cm", lev:"8 à 15 jours", cyc:"3 mois",
  amis:["Carotte","Radis","Navet","Laitue / Salade","Concombre"],
  ennemis:["Ail","Oignon","Échalote","Poireau","Tomate"],
  perma:"Enrichit le sol en azote. Sème un engrais vert derrière une fois récolté. Les semis de novembre donnent une récolte très précoce en mai.",
  conseils:"Prévoir un support même pour les variétés dites naines." },

{ id:"feve", nom:"Fève", latin:"Vicia faba", cat:"legume", fam:"Fabacées", viv:false,
  sa:[], sp:[2,3,10,11], pl:[], re:[5,6,7],
  expo:"Soleil", sol:"Tous types, argileux accepté", eau:"Modéré",
  esp:"15 cm sur le rang, 50 cm entre rangs", prof:"5 cm", lev:"10 à 20 jours", cyc:"4 mois",
  amis:["Pomme de terre","Épinard","Laitue / Salade","Sarriette vivace"],
  ennemis:["Ail","Oignon","Échalote"],
  perma:"Excellent couvre-sol d'hiver qui fixe l'azote. Semis en novembre = récolte en mai et sol amélioré gratuitement.",
  conseils:"Pincer le sommet dès les premières gousses : ça stoppe les pucerons noirs et grossit les fèves." },

{ id:"carotte", nom:"Carotte", latin:"Daucus carota", cat:"legume", fam:"Apiacées", viv:false,
  sa:[], sp:[3,4,5,6,7], pl:[], re:[6,7,8,9,10,11],
  expo:"Soleil", sol:"Meuble, sableux, sans cailloux ni fumier frais", eau:"Régulier jusqu'à la levée",
  esp:"5 cm sur le rang, 25 cm entre rangs", prof:"1 cm", lev:"15 à 21 jours", cyc:"3 à 5 mois",
  amis:["Poireau","Oignon","Ail","Radis","Laitue / Salade","Romarin","Sauge officinale"],
  ennemis:["Aneth","Persil","Betterave rouge"],
  perma:"Le duo carotte + poireau est LE classique : chacun repousse la mouche de l'autre. Sème très clair pour éviter l'éclaircissage, dont l'odeur attire la mouche.",
  conseils:"Garde le sol humide jusqu'à la levée, c'est le point critique. Un voile anti-insectes règle définitivement le problème de la mouche." },

{ id:"radis", nom:"Radis", latin:"Raphanus sativus", cat:"legume", fam:"Brassicacées", viv:false,
  sa:[2], sp:[3,4,5,6,7,8,9], pl:[], re:[4,5,6,7,8,9,10],
  expo:"Mi-ombre l'été, soleil au printemps", sol:"Léger, frais", eau:"Très régulier (sinon piquant et creux)",
  esp:"3 cm", prof:"1 cm", lev:"3 à 5 jours", cyc:"1 mois",
  amis:["Carotte","Laitue / Salade","Petit pois","Haricot nain","Capucine","Épinard"],
  ennemis:["Chou pommé","Concombre"],
  perma:"Parfait pour occuper les espaces libres entre des cultures lentes (choux, poireaux). Sème toutes les 2 semaines.",
  conseils:"Le radis d'été monte vite : mets-le à l'ombre des tomates ou des haricots à rames." },

{ id:"navet", nom:"Navet", latin:"Brassica rapa", cat:"legume", fam:"Brassicacées", viv:false,
  sa:[], sp:[3,4,7,8,9], pl:[], re:[5,6,7,10,11,12],
  expo:"Soleil ou mi-ombre", sol:"Frais, riche en humus", eau:"Régulier",
  esp:"10 cm", prof:"1 cm", lev:"5 à 8 jours", cyc:"2 à 3 mois",
  amis:["Petit pois","Laitue / Salade","Céleri branche","Menthe poivrée"],
  ennemis:["Chou pommé","Ail","Radis"],
  perma:"Les semis d'août-septembre donnent les meilleurs navets : plus doux et épargnés par les altises.",
  conseils:"Récolter jeune : passé 8 cm il devient filandreux." },

{ id:"betterave", nom:"Betterave rouge", latin:"Beta vulgaris", cat:"legume", fam:"Chénopodiacées", viv:false,
  sa:[3], sp:[4,5,6], pl:[5], re:[7,8,9,10,11],
  expo:"Soleil", sol:"Profond, meuble, pas de fumier frais", eau:"Modéré mais régulier",
  esp:"12 cm sur le rang, 30 cm entre rangs", prof:"2 cm", lev:"10 à 15 jours", cyc:"3 à 4 mois",
  amis:["Laitue / Salade","Chou pommé","Oignon","Haricot nain"],
  ennemis:["Haricot à rames","Poireau","Maïs doux"],
  perma:"Les feuilles se mangent comme des blettes : ne les jette pas. Se conserve tout l'hiver dans du sable au frais.",
  conseils:"Chaque graine est en fait un glomérule qui donne 2-3 plants : il faudra éclaircir." },

{ id:"panais", nom:"Panais", latin:"Pastinaca sativa", cat:"legume", fam:"Apiacées", viv:false,
  sa:[], sp:[3,4,5], pl:[], re:[10,11,12,1,2],
  expo:"Soleil", sol:"Profond, meuble, frais", eau:"Régulier",
  esp:"15 cm sur le rang, 35 cm entre rangs", prof:"1,5 cm", lev:"20 à 30 jours", cyc:"6 à 8 mois",
  amis:["Radis","Laitue / Salade","Ail","Petit pois"],
  ennemis:["Carotte","Céleri branche"],
  perma:"Légume d'hiver parfait : il se garde en terre et devient plus sucré après les gelées. Utilise des graines de l'année, elles perdent vite leur pouvoir germinatif.",
  conseils:"Germination très lente : sème quelques radis sur le même rang pour marquer l'emplacement." },

{ id:"pomme-de-terre", nom:"Pomme de terre", latin:"Solanum tuberosum", cat:"legume", fam:"Solanacées", viv:false,
  sa:[], sp:[], pl:[3,4,5], re:[6,7,8,9],
  expo:"Soleil", sol:"Meuble, riche, plutôt acide", eau:"Régulier à la floraison",
  esp:"35 cm sur le rang, 65 cm entre rangs", prof:"10 cm", lev:"20 à 30 jours", cyc:"3 à 4 mois",
  amis:["Haricot nain","Chou pommé","Maïs doux","Œillet d'Inde","Capucine"],
  ennemis:["Tomate","Courge butternut","Concombre","Céleri branche"],
  perma:"Méthode sans effort : pose les plants sur le sol et recouvre de 30 cm de paille/foin. Récolte à la main, sans bêcher. Idéal pour défricher une nouvelle parcelle.",
  conseils:"Pré-germer les plants un mois avant, dans un endroit clair et frais. Butter 2 fois." },

{ id:"oignon", nom:"Oignon", latin:"Allium cepa", cat:"legume", fam:"Amaryllidacées", viv:false,
  sa:[2], sp:[3,8,9], pl:[3,4,9,10], re:[7,8,9],
  expo:"Plein soleil", sol:"Léger, drainé, surtout pas de fumier frais", eau:"Faible, on arrête 3 semaines avant récolte",
  esp:"10 cm sur le rang, 25 cm entre rangs", prof:"Bulbe affleurant", lev:"12 à 20 jours", cyc:"5 mois",
  amis:["Carotte","Betterave rouge","Fraisier","Laitue / Salade","Tomate","Camomille romaine"],
  ennemis:["Haricot nain","Petit pois","Fève","Chou pommé"],
  perma:"En bordure des carottes et des fraisiers : son odeur brouille les ravageurs. Sol détrempé = pourriture assurée, préfère une petite butte.",
  conseils:"Récolter quand le feuillage est couché et jauni, puis sécher au soleil 8 jours avant de stocker." },

{ id:"ail", nom:"Ail", latin:"Allium sativum", cat:"legume", fam:"Amaryllidacées", viv:false,
  sa:[], sp:[], pl:[10,11,12,2,3], re:[6,7,8],
  expo:"Plein soleil", sol:"Léger, drainé, aucune fumure", eau:"Quasiment aucun arrosage",
  esp:"12 cm sur le rang, 25 cm entre rangs", prof:"3 cm, pointe vers le haut", lev:"15 à 25 jours", cyc:"8 mois (plantation d'automne)",
  amis:["Fraisier","Tomate","Carotte","Betterave rouge"],
  ennemis:["Haricot nain","Petit pois","Fève","Chou pommé"],
  perma:"Antifongique naturel : plante-le près des fraisiers et des tomates. Une décoction d'ail traite le mildiou et l'oïdium.",
  conseils:"Ail blanc/violet = plantation d'automne. Ail rose = plantation de février. L'ail d'automne est bien plus gros." },

{ id:"echalote", nom:"Échalote", latin:"Allium ascalonicum", cat:"legume", fam:"Amaryllidacées", viv:false,
  sa:[], sp:[], pl:[10,11,2,3], re:[6,7,8],
  expo:"Plein soleil", sol:"Léger, drainé", eau:"Très faible",
  esp:"15 cm sur le rang, 25 cm entre rangs", prof:"Pointe affleurante", lev:"15 jours", cyc:"6 mois",
  amis:["Carotte","Fraisier","Tomate","Betterave rouge"],
  ennemis:["Haricot nain","Petit pois","Fève"],
  perma:"Ne jamais l'enterrer, elle pourrirait. Sur une petite butte si ton sol est lourd.",
  conseils:"Dicton : plantée à la Sainte-Catherine (25 novembre), récoltée à la Saint-Jean (24 juin)." },

{ id:"poireau", nom:"Poireau", latin:"Allium porrum", cat:"legume", fam:"Amaryllidacées", viv:false,
  sa:[2,3], sp:[3,4], pl:[5,6,7,8], re:[9,10,11,12,1,2,3],
  expo:"Soleil", sol:"Riche, profond, frais", eau:"Régulier",
  esp:"12 cm sur le rang, 30 cm entre rangs", prof:"Repiquer à 10 cm de profondeur", lev:"15 à 20 jours", cyc:"5 à 7 mois",
  amis:["Carotte","Fraisier","Céleri branche","Tomate","Laitue / Salade"],
  ennemis:["Haricot nain","Petit pois","Fève","Betterave rouge"],
  perma:"Au repiquage, raccourcis racines et feuilles d'un tiers : ça relance la plante. Contre le ver du poireau, un voile anti-insectes de mai à octobre est la seule méthode vraiment efficace.",
  conseils:"Butter au fur et à mesure pour un long fût blanc. Se récolte tout l'hiver selon les besoins." },

{ id:"laitue", nom:"Laitue / Salade", latin:"Lactuca sativa", cat:"legume", fam:"Astéracées", viv:false,
  sa:[1,2,3,8,9], sp:[3,4,5,6,7,8], pl:[3,4,5,6,7,8,9], re:[5,6,7,8,9,10,11],
  expo:"Soleil au printemps, mi-ombre en été", sol:"Frais, riche en humus", eau:"Régulier, le matin",
  esp:"25 cm en tous sens", prof:"0,5 cm", lev:"4 à 8 jours", cyc:"6 à 10 semaines",
  amis:["Carotte","Radis","Fraisier","Concombre","Poireau","Betterave rouge"],
  ennemis:["Persil","Céleri branche"],
  perma:"Sème 10 salades toutes les 2 semaines plutôt que 60 d'un coup. En été, place-les à l'ombre des tomates ou des haricots grimpants pour éviter la montée en graine.",
  conseils:"Ne pas enterrer le collet au repiquage, sinon pourriture. Les graines ne germent plus au-dessus de 25°C." },

{ id:"mache", nom:"Mâche", latin:"Valerianella locusta", cat:"legume", fam:"Caprifoliacées", viv:false,
  sa:[], sp:[8,9,10], pl:[], re:[10,11,12,1,2,3],
  expo:"Soleil d'automne", sol:"Plutôt ferme et tassé", eau:"Régulier jusqu'à la levée",
  esp:"10 cm", prof:"0,5 cm", lev:"10 à 15 jours", cyc:"2 à 3 mois",
  amis:["Poireau","Oignon","Chou pommé","Fraisier"],
  ennemis:[],
  perma:"Le légume idéal pour ne pas laisser le sol nu en hiver. Se sème derrière les pommes de terre ou les haricots.",
  conseils:"Contrairement au reste, elle aime un sol tassé : plombe bien après le semis. Résiste à -15°C." },

{ id:"roquette", nom:"Roquette", latin:"Eruca sativa", cat:"legume", fam:"Brassicacées", viv:false,
  sa:[2,3], sp:[3,4,5,8,9], pl:[], re:[4,5,6,7,9,10,11],
  expo:"Mi-ombre en été", sol:"Frais, riche", eau:"Régulier (sinon très piquante)",
  esp:"10 cm", prof:"0,5 cm", lev:"5 jours", cyc:"6 semaines",
  amis:["Laitue / Salade","Épinard","Carotte"],
  ennemis:["Chou pommé"],
  perma:"Se ressème toute seule si tu laisses quelques pieds monter en fleurs — et les fleurs sont comestibles et adorées des abeilles.",
  conseils:"Coupe feuille à feuille, la plante repart plusieurs fois." },

{ id:"epinard", nom:"Épinard", latin:"Spinacia oleracea", cat:"legume", fam:"Chénopodiacées", viv:false,
  sa:[], sp:[3,4,8,9], pl:[], re:[5,6,10,11,12,3],
  expo:"Mi-ombre", sol:"Riche en azote, frais", eau:"Abondant",
  esp:"10 cm sur le rang, 30 cm entre rangs", prof:"2 cm", lev:"8 à 12 jours", cyc:"2 mois",
  amis:["Fraisier","Chou pommé","Haricot nain","Fève","Radis"],
  ennemis:["Betterave rouge","Blette / Poirée"],
  perma:"Engrais vert comestible : ses racines profondes décompactent le sol. Semis d'automne = récolte de mars, quand le potager est vide.",
  conseils:"Monte très vite en graine dès qu'il a chaud ou soif : évite les semis de mai-juin." },

{ id:"blette", nom:"Blette / Poirée", latin:"Beta vulgaris var. cicla", cat:"legume", fam:"Chénopodiacées", viv:false,
  sa:[3], sp:[4,5,6], pl:[5,6], re:[6,7,8,9,10,11],
  expo:"Soleil ou mi-ombre", sol:"Riche, profond", eau:"Régulier",
  esp:"40 cm en tous sens", prof:"2 cm", lev:"10 jours", cyc:"3 mois",
  amis:["Carotte","Radis","Chou pommé","Haricot nain"],
  ennemis:["Épinard","Betterave rouge"],
  perma:"Ultra productive : 5 pieds nourrissent une famille de mai à décembre. Coupe les feuilles extérieures, le cœur repart indéfiniment.",
  conseils:"Peut passer l'hiver et repartir au printemps avant de monter en graine." },

{ id:"chou-pomme", nom:"Chou pommé", latin:"Brassica oleracea capitata", cat:"legume", fam:"Brassicacées", viv:false,
  sa:[2,3], sp:[4,5,6], pl:[5,6,7], re:[8,9,10,11,12,1],
  expo:"Soleil", sol:"Riche, ferme, calcaire", eau:"Régulier et abondant",
  esp:"50 cm en tous sens", prof:"1 cm", lev:"6 à 10 jours", cyc:"4 à 6 mois",
  amis:["Céleri branche","Aneth","Menthe poivrée","Romarin","Thym","Bourrache officinale","Betterave rouge"],
  ennemis:["Fraisier","Tomate","Ail","Oignon"],
  perma:"Plante de la menthe, du thym ou de l'aneth entre les choux : leur odeur perturbe la piéride. Un voile anti-insectes = tranquillité totale. Ne jamais remettre un chou au même endroit avant 4 ans (hernie).",
  conseils:"Gros consommateur : composte généreusement avant plantation." },

{ id:"chou-fleur", nom:"Chou-fleur", latin:"Brassica oleracea botrytis", cat:"legume", fam:"Brassicacées", viv:false,
  sa:[2,3,4], sp:[5], pl:[5,6,7], re:[9,10,11,12],
  expo:"Soleil", sol:"Très riche, frais, profond", eau:"Abondant et sans interruption",
  esp:"60 cm en tous sens", prof:"1 cm", lev:"7 jours", cyc:"5 mois",
  amis:["Céleri branche","Aneth","Bourrache officinale","Menthe poivrée"],
  ennemis:["Fraisier","Tomate","Oignon"],
  perma:"Le plus exigeant des choux : le moindre manque d'eau bloque définitivement la pomme. Paille épais.",
  conseils:"Casse une feuille sur la pomme pour la garder bien blanche." },

{ id:"brocoli", nom:"Brocoli", latin:"Brassica oleracea italica", cat:"legume", fam:"Brassicacées", viv:false,
  sa:[2,3,4], sp:[5], pl:[5,6,7], re:[8,9,10,11],
  expo:"Soleil", sol:"Riche, frais", eau:"Régulier",
  esp:"50 cm en tous sens", prof:"1 cm", lev:"7 jours", cyc:"3 à 4 mois",
  amis:["Céleri branche","Aneth","Camomille romaine","Menthe poivrée"],
  ennemis:["Fraisier","Tomate"],
  perma:"Après la tête centrale, laisse le pied en place : il produit des petites pousses latérales pendant des semaines.",
  conseils:"Récolte avant que les boutons ne s'ouvrent en fleurs jaunes." },

{ id:"chou-kale", nom:"Chou kale", latin:"Brassica oleracea acephala", cat:"legume", fam:"Brassicacées", viv:false,
  sa:[3,4], sp:[5,6], pl:[6,7], re:[10,11,12,1,2,3],
  expo:"Soleil", sol:"Riche", eau:"Régulier",
  esp:"50 cm en tous sens", prof:"1 cm", lev:"7 jours", cyc:"4 mois",
  amis:["Céleri branche","Menthe poivrée","Thym","Betterave rouge"],
  ennemis:["Fraisier","Tomate"],
  perma:"Le chou le plus facile et le plus rustique : il tient jusqu'à -15°C et se récolte feuille par feuille tout l'hiver.",
  conseils:"Bien meilleur après une gelée, qui le rend sucré." },

{ id:"chou-bruxelles", nom:"Chou de Bruxelles", latin:"Brassica oleracea gemmifera", cat:"legume", fam:"Brassicacées", viv:false,
  sa:[3,4], sp:[4,5], pl:[5,6], re:[10,11,12,1,2],
  expo:"Soleil", sol:"Riche et ferme (surtout pas de sol meuble)", eau:"Régulier",
  esp:"60 cm en tous sens", prof:"1 cm", lev:"7 jours", cyc:"7 mois",
  amis:["Céleri branche","Aneth","Menthe poivrée"],
  ennemis:["Fraisier","Tomate"],
  perma:"Tasse bien le sol au pied, sinon les choux ne se forment pas et restent ouverts.",
  conseils:"Pincer la tête du plant en septembre pour faire grossir tous les choux d'un coup." },

{ id:"celeri-branche", nom:"Céleri branche", latin:"Apium graveolens", cat:"legume", fam:"Apiacées", viv:false,
  sa:[2,3], sp:[], pl:[5], re:[8,9,10,11],
  expo:"Soleil ou mi-ombre", sol:"Très riche, lourd, frais", eau:"Très abondant",
  esp:"30 cm en tous sens", prof:"À peine recouvert (la graine a besoin de lumière)", lev:"15 à 25 jours", cyc:"5 mois",
  amis:["Chou pommé","Poireau","Tomate","Haricot nain"],
  ennemis:["Persil","Carotte","Maïs doux","Pomme de terre"],
  perma:"Le meilleur compagnon des choux : son odeur forte désoriente la piéride.",
  conseils:"Il lui faut vraiment beaucoup d'eau : plante-le dans un léger creux qui retient l'arrosage." },

{ id:"celeri-rave", nom:"Céleri-rave", latin:"Apium graveolens rapaceum", cat:"legume", fam:"Apiacées", viv:false,
  sa:[2,3], sp:[], pl:[5], re:[9,10,11],
  expo:"Soleil", sol:"Riche, profond, frais", eau:"Très abondant",
  esp:"35 cm en tous sens", prof:"En surface", lev:"20 jours", cyc:"6 mois",
  amis:["Chou pommé","Poireau","Haricot nain","Tomate"],
  ennemis:["Persil","Carotte","Maïs doux"],
  perma:"Planter le collet au ras du sol, jamais enterré. Dégage la terre autour de la boule en fin d'été pour qu'elle grossisse.",
  conseils:"Se conserve tout l'hiver en cave dans du sable." },

{ id:"fenouil-bulbe", nom:"Fenouil bulbeux", latin:"Foeniculum vulgare azoricum", cat:"legume", fam:"Apiacées", viv:false,
  sa:[3], sp:[5,6,7], pl:[6,7], re:[8,9,10,11],
  expo:"Soleil", sol:"Riche, frais, profond", eau:"Très régulier",
  esp:"30 cm en tous sens", prof:"1 cm", lev:"10 jours", cyc:"3 à 4 mois",
  amis:[],
  ennemis:["Tomate","Haricot nain","Chou pommé","Coriandre"],
  perma:"Mauvais voisin pour presque tout le potager : isole-le dans un coin ou en bordure.",
  conseils:"Les semis avant juin montent en graine : privilégie juin-juillet. Butter le bulbe pour le blanchir." },

{ id:"artichaut", nom:"Artichaut", latin:"Cynara scolymus", cat:"legume", fam:"Astéracées", viv:true,
  sa:[2,3], sp:[], pl:[4,5,9,10], re:[6,7,8,9],
  expo:"Plein soleil, abrité", sol:"Riche, profond, très drainé", eau:"Généreux en été",
  esp:"1 m en tous sens", prof:"1 cm", lev:"15 jours", cyc:"1 an (pleine production la 2e année)",
  amis:["Fève","Laitue / Salade","Petit pois"],
  ennemis:[],
  perma:"Vivace 4-5 ans. Divise les œilletons au printemps pour renouveler la plantation gratuitement. Butte et paille en novembre contre le gel.",
  conseils:"Occupe beaucoup de place mais produit chaque année sans presque rien faire." },

{ id:"asperge", nom:"Asperge", latin:"Asparagus officinalis", cat:"legume", fam:"Asparagacées", viv:true,
  sa:[], sp:[], pl:[3,4], re:[4,5,6],
  expo:"Plein soleil", sol:"Sableux, très drainé, profond", eau:"Faible une fois installée",
  esp:"50 cm sur le rang, 1,5 m entre rangs", prof:"Griffes à 20 cm", lev:"—", cyc:"3 ans avant la 1re récolte",
  amis:["Tomate","Persil","Basilic"],
  ennemis:["Ail","Oignon","Betterave rouge"],
  perma:"Investissement long terme : une aspergeraie produit 15 à 20 ans. Ne récolte rien les 2 premières années, laisse les fougères nourrir les griffes.",
  conseils:"Coupe les fougères sèches en novembre et paille de compost." },

{ id:"butternut", nom:"Courge butternut", latin:"Cucurbita moschata", cat:"legume", fam:"Cucurbitacées", viv:false,
  sa:[4], sp:[5], pl:[5,6], re:[9,10],
  expo:"Plein soleil", sol:"Très riche, compost", eau:"Abondant jusqu'en août puis stop",
  esp:"1,5 m en tous sens", prof:"3 cm", lev:"6 à 10 jours", cyc:"4 à 5 mois",
  amis:["Maïs doux","Haricot à rames","Capucine","Bourrache officinale"],
  ennemis:["Pomme de terre"],
  perma:"Couvre-sol naturel : ses grandes feuilles étouffent les herbes indésirables. Plante-la en bord de compost et laisse-la courir.",
  conseils:"Récolte avant les gelées, quand le pédoncule est sec et liégeux. Se conserve 6 mois à 15°C." },

{ id:"potiron", nom:"Potiron / Potimarron", latin:"Cucurbita maxima", cat:"legume", fam:"Cucurbitacées", viv:false,
  sa:[4], sp:[5], pl:[5,6], re:[9,10],
  expo:"Plein soleil", sol:"Très riche", eau:"Abondant en été",
  esp:"2 m en tous sens", prof:"3 cm", lev:"6 à 10 jours", cyc:"4 mois",
  amis:["Maïs doux","Haricot à rames","Capucine"],
  ennemis:["Pomme de terre","Concombre"],
  perma:"Glisse une tuile ou une planche sous chaque fruit pour éviter la pourriture au contact du sol humide.",
  conseils:"Limite à 3-4 fruits par pied pour qu'ils grossissent bien." },

{ id:"melon", nom:"Melon", latin:"Cucumis melo", cat:"legume", fam:"Cucurbitacées", viv:false,
  sa:[3,4], sp:[5], pl:[5,6], re:[7,8,9],
  expo:"Plein soleil, très chaud", sol:"Riche, drainé, réchauffé", eau:"Régulier puis stop 15 jours avant récolte",
  esp:"1 m en tous sens", prof:"2 cm", lev:"5 à 8 jours", cyc:"4 mois",
  amis:["Maïs doux","Capucine","Bourrache officinale","Basilic"],
  ennemis:["Concombre","Pomme de terre"],
  perma:"Sous bâche ou paillage sombre pour réchauffer le sol. Une seule tige avec 4-5 fruits maximum.",
  conseils:"Mûr quand le pédoncule se craquelle et que l'odeur devient forte." },

{ id:"mais-doux", nom:"Maïs doux", latin:"Zea mays", cat:"legume", fam:"Poacées", viv:false,
  sa:[4], sp:[5,6], pl:[5,6], re:[8,9,10],
  expo:"Plein soleil", sol:"Riche, profond", eau:"Abondant à la floraison",
  esp:"40 cm en tous sens, planté en bloc carré", prof:"3 cm", lev:"8 à 12 jours", cyc:"3 mois",
  amis:["Haricot à rames","Courge butternut","Concombre","Capucine"],
  ennemis:["Betterave rouge","Céleri branche","Tomate"],
  perma:"Toujours en bloc carré (4 rangs minimum), jamais en ligne : la pollinisation se fait par le vent. Sert de tuteur vivant aux haricots grimpants.",
  conseils:"Récolte quand les soies brunissent et qu'un grain percé rend un jus laiteux." },

{ id:"topinambour", nom:"Topinambour", latin:"Helianthus tuberosus", cat:"legume", fam:"Astéracées", viv:true,
  sa:[], sp:[], pl:[2,3,4,11,12], re:[10,11,12,1,2,3],
  expo:"Soleil", sol:"N'importe lequel", eau:"Aucun besoin",
  esp:"40 cm sur le rang, 80 cm entre rangs", prof:"10 cm", lev:"3 à 4 semaines", cyc:"7 mois",
  amis:["Maïs doux"],
  ennemis:["Tout le reste (très envahissant)"],
  perma:"Zéro entretien, énorme production, se récolte tout l'hiver. ATTENTION : très envahissant, réserve-lui un coin isolé — il ne partira plus jamais.",
  conseils:"Sert aussi de haie brise-vent estivale (2 à 3 m de haut) et de fleur à butiner en septembre." },

{ id:"rhubarbe", nom:"Rhubarbe", latin:"Rheum rhabarbarum", cat:"legume", fam:"Polygonacées", viv:true,
  sa:[], sp:[], pl:[3,4,10,11], re:[4,5,6,7],
  expo:"Mi-ombre", sol:"Très riche, frais, profond", eau:"Généreux",
  esp:"1,2 m en tous sens", prof:"Bourgeon affleurant", lev:"—", cyc:"1re récolte la 2e année",
  amis:["Chou pommé","Haricot nain","Ail"],
  ennemis:[],
  perma:"Vivace de 10 ans et plus. Un seau de compost chaque automne au pied et elle produit sans rien demander. Les feuilles (toxiques à manger) font un excellent paillage ou purin anti-pucerons.",
  conseils:"Ne jamais couper : tire sur le pétiole en le tournant. Ne récolte pas la 1re année. Coupe les fleurs dès leur apparition." },

{ id:"chicoree", nom:"Chicorée frisée / Scarole", latin:"Cichorium endivia", cat:"legume", fam:"Astéracées", viv:false,
  sa:[4,5], sp:[5,6,7], pl:[6,7,8], re:[8,9,10,11,12],
  expo:"Soleil, mi-ombre en été", sol:"Frais, riche", eau:"Régulier",
  esp:"30 cm en tous sens", prof:"0,5 cm", lev:"5 à 8 jours", cyc:"3 mois",
  amis:["Carotte","Poireau","Radis"],
  ennemis:["Laitue / Salade"],
  perma:"Prend le relais des salades d'été quand elles montent en graine. Résiste bien au froid sous voile.",
  conseils:"Blanchir en couvrant le cœur d'une assiette 10 jours avant récolte pour enlever l'amertume." },

{ id:"fraisier", nom:"Fraisier", latin:"Fragaria x ananassa", cat:"legume", fam:"Rosacées", viv:true,
  sa:[], sp:[], pl:[3,4,8,9,10], re:[5,6,7,8,9],
  expo:"Soleil, mi-ombre en climat chaud", sol:"Riche en humus, acide, drainé", eau:"Régulier au pied",
  esp:"30 cm sur le rang, 50 cm entre rangs", prof:"Collet au ras du sol", lev:"—", cyc:"1 an",
  amis:["Ail","Oignon","Poireau","Épinard","Bourrache officinale","Thym"],
  ennemis:["Chou pommé","Pomme de terre","Tomate"],
  perma:"Paille sous les fruits (d'où le nom !) pour éviter la pourriture. Les stolons donnent des plants gratuits à repiquer en août. Renouvelle la plantation tous les 3 ans.",
  conseils:"La bourrache plantée à côté attire les pollinisateurs et augmente nettement la récolte." },

{ id:"pourpier", nom:"Pourpier d'été", latin:"Portulaca oleracea", cat:"legume", fam:"Portulacacées", viv:false,
  sa:[], sp:[5,6,7], pl:[], re:[6,7,8,9],
  expo:"Plein soleil", sol:"Léger, même pauvre et sec", eau:"Faible",
  esp:"20 cm", prof:"Semis en surface", lev:"7 à 10 jours", cyc:"6 semaines",
  amis:["Maïs doux","Tomate"],
  ennemis:[],
  perma:"Couvre-sol comestible qui pousse là où rien ne pousse. Très riche en oméga-3.",
  conseils:"Se ressème seul chaque année. Se récolte en coupant les tiges tendres." },

{ id:"oseille", nom:"Oseille", latin:"Rumex acetosa", cat:"legume", fam:"Polygonacées", viv:true,
  sa:[3], sp:[4,5,8,9], pl:[4,5,9], re:[4,5,6,7,8,9,10],
  expo:"Mi-ombre", sol:"Frais, riche", eau:"Régulier",
  esp:"30 cm en tous sens", prof:"1 cm", lev:"10 jours", cyc:"3 mois",
  amis:["Fraisier","Chou pommé"],
  ennemis:[],
  perma:"Vivace increvable qui produit dès mars, quand il n'y a rien d'autre au potager. Divise la touffe tous les 4 ans.",
  conseils:"Coupe les hampes florales pour prolonger la production de feuilles tendres. À consommer avec modération (acide oxalique)." },

{ id:"capucine", nom:"Capucine", latin:"Tropaeolum majus", cat:"legume", fam:"Tropaeolacées", viv:false,
  sa:[3,4], sp:[4,5], pl:[5], re:[6,7,8,9,10],
  expo:"Soleil", sol:"Pauvre de préférence (trop riche = que des feuilles)", eau:"Faible",
  esp:"40 cm", prof:"2 cm", lev:"10 jours", cyc:"2 mois",
  amis:["Tomate","Courgette","Chou pommé","Pomme de terre","Haricot à rames"],
  ennemis:[],
  perma:"Plante-piège n°1 du potager : les pucerons noirs s'y jettent et laissent tes légumes tranquilles. Fleurs et feuilles comestibles (goût poivré), boutons floraux à confire comme des câpres.",
  conseils:"Se ressème seule d'année en année. Ne pas l'arroser ni la nourrir." },

{ id:"oeillet-inde", nom:"Œillet d'Inde", latin:"Tagetes patula", cat:"legume", fam:"Astéracées", viv:false,
  sa:[3,4], sp:[5], pl:[5,6], re:[6,7,8,9,10],
  expo:"Soleil", sol:"Ordinaire", eau:"Modéré",
  esp:"25 cm", prof:"0,5 cm", lev:"7 jours", cyc:"3 mois",
  amis:["Tomate","Pomme de terre","Aubergine","Poivron / Piment","Fraisier"],
  ennemis:[],
  perma:"Ses racines émettent une substance qui élimine les nématodes du sol. À planter systématiquement entre les tomates et les pommes de terre. Attire aussi les syrphes, prédateurs des pucerons.",
  conseils:"Coupe les fleurs fanées pour une floraison jusqu'aux gelées. Se ressème seul." }

];
